repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args:
          - --line-length=88
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: cmd
        args: ["/c", "python -m pytest ./tests"]
        files: ^integration/
        language: system
